name: LintMypy

on:
  push:
    paths:
    - "**.py"
    - ".github/workflows/lint_mypy.yml"
  pull_request:
    paths:
    - "**.py"
    - ".github/workflows/lint_mypy.yml"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install pylint
    - run: pylint mesonbuild

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install mypy
    - run: |
        mypy run_project_tests.py run_tests.py
        mypy mesonbuild/mtest.py mesonbuild/minit.py mesonbuild/msetup.py
        mypy mesonbuild/wrap/ tools/
        mypy mesonbuild/modules/fs.py mesonbuild/dependencies/mpi.py mesonbuild/dependencies/hdf5.py
